package com.Pirk.Pirk.models;

import java.math.BigDecimal;
import lombok.Builder;
import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class PaymentRequest {

   
    private String cardNumber;
    private String lastFourDigits;
    private String paymentMethod;
    private BigDecimal amount;
    private Long buyerId;
    private Long orderId;
    private String cvv;
    private String expirationDate;

    // Getters and setters for each field will be auto-generated by Lombok's @Data annotation
}
